//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alarma()
        {
            this.AlarmaGeocerca = new HashSet<AlarmaGeocerca>();
            this.Alerta = new HashSet<Alerta>();
            this.AlarmaDestinatarios = new HashSet<AlarmaDestinatarios>();
            this.AlarmaVehiculo = new HashSet<AlarmaVehiculo>();
        }
    
        public int CodAlarma { get; set; }
        public bool email { get; set; }
        public bool sms { get; set; }
        public string NombreAlarma { get; set; }
        public int CodTipoAlarma { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaModif { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public int CodCategoria { get; set; }
        public Nullable<bool> Activa { get; set; }
        public Nullable<int> CantidadEnvio { get; set; }
        public Nullable<int> TiempoEnvio { get; set; }
        public Nullable<int> IntervaloEnvio { get; set; }
        public string NIT { get; set; }
        public Nullable<double> Velocidad { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public Nullable<double> Distancia { get; set; }
        public Nullable<int> Temperatura { get; set; }
        public Nullable<double> Velocidad2 { get; set; }
        public Nullable<int> Tiempo2 { get; set; }
        public Nullable<double> Distancia2 { get; set; }
        public Nullable<int> Temperatura2 { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHora2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmaGeocerca> AlarmaGeocerca { get; set; }
        public virtual CategoriaAlarma CategoriaAlarma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        public virtual TipoAlarma TipoAlarma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmaDestinatarios> AlarmaDestinatarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmaVehiculo> AlarmaVehiculo { get; set; }
    }
}
