//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta2
    {
        public long ID { get; set; }
        public string NroPlaca { get; set; }
        public int CodAlarma { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<long> IDFin { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public int EstadoEnvio { get; set; }
        public Nullable<int> CantidadEmail { get; set; }
    }
}
