//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public long ID { get; set; }
        public int CodSeguimiento { get; set; }
        public string NroPlaca { get; set; }
        public int CodAlarma { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaHora { get; set; }
        public bool Visto { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<long> IDTrama { get; set; }
        public int CodigoGEO { get; set; }
        public int Ultimo { get; set; }
        public bool Procesado { get; set; }
    
        public virtual Alarma Alarma { get; set; }
        public virtual Seguimiento Seguimiento { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
