//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaGPS
    {
        public int id { get; set; }
        public string imei { get; set; }
        public string nit { get; set; }
        public Nullable<bool> estado { get; set; }
        public string usuarioReg { get; set; }
        public Nullable<System.DateTime> fechaReg { get; set; }
        public string usuarioMod { get; set; }
        public Nullable<System.DateTime> fechaMod { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual GPS GPS { get; set; }
    }
}
