//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPSTrama
    {
        public long ID { get; set; }
        public string IMEI { get; set; }
        public long IDInicio { get; set; }
        public long IDFin { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool Procesado { get; set; }
        public int PID { get; set; }
        public int Intervalo { get; set; }
    }
}
