//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdButton
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdButton()
        {
            this.EmpresaIDButton = new HashSet<EmpresaIDButton>();
            this.IDButtonGps = new HashSet<IDButtonGps>();
        }
    
        public int ID { get; set; }
        public string Keys { get; set; }
        public string Alias { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuaReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string UsuaMod { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaIDButton> EmpresaIDButton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDButtonGps> IDButtonGps { get; set; }
    }
}
