//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona1
    {
        public string CI { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Contacto { get; set; }
        public string TelfContacto { get; set; }
        public Nullable<int> CodArea { get; set; }
        public string PswUsuario { get; set; }
        public bool Estado { get; set; }
        public int CodTipo { get; set; }
        public string CategoriaL { get; set; }
        public Nullable<System.DateTime> FechaVigL { get; set; }
        public Nullable<System.DateTime> FechaVigDefL { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaModif { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public string IDButton { get; set; }
        public string IdUser { get; set; }
    }
}
