//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.AlarmaDestinatarios = new HashSet<AlarmaDestinatarios>();
            this.UsuarioEmpresa = new HashSet<UsuarioEmpresa>();
            this.UsuarioVehiculo = new HashSet<UsuarioVehiculo>();
            this.VehiculoConductor = new HashSet<VehiculoConductor>();
        }
    
        public string CI { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Contacto { get; set; }
        public string TelfContacto { get; set; }
        public Nullable<int> CodArea { get; set; }
        public string PswUsuario { get; set; }
        public bool Estado { get; set; }
        public int CodTipo { get; set; }
        public string CategoriaL { get; set; }
        public Nullable<System.DateTime> FechaVigL { get; set; }
        public Nullable<System.DateTime> FechaVigDefL { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaModif { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public string IDButton { get; set; }
        public string IdUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmaDestinatarios> AlarmaDestinatarios { get; set; }
        public virtual Area Area { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioEmpresa> UsuarioEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioVehiculo> UsuarioVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoConductor> VehiculoConductor { get; set; }
    }
}
