//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteTemp
    {
        public long ID { get; set; }
        public string Usuario { get; set; }
        public string NroPlaca { get; set; }
        public int CodTipoAlarma { get; set; }
        public int IDInicio { get; set; }
        public int IDFin { get; set; }
        public int CodigoGEO { get; set; }
        public int Ultimo { get; set; }
    }
}
