//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trama3
    {
        public long ID { get; set; }
        public long IDTrama { get; set; }
        public int Procesado { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<int> t_control { get; set; }
        public Nullable<int> t_detencion_maxima { get; set; }
        public Nullable<int> t_detencion_minima { get; set; }
        public Nullable<int> t_itinerario { get; set; }
        public Nullable<int> t_velocidad_masiva { get; set; }
        public Nullable<int> t_entrada_salida { get; set; }
        public Nullable<int> t_kilometraje_maximo { get; set; }
        public Nullable<int> t_temperatura_maxima { get; set; }
        public Nullable<int> t_temperatura_minima { get; set; }
        public Nullable<int> t_apertura_cierre { get; set; }
        public Nullable<int> t_voltaje { get; set; }
        public Nullable<int> t_entrada { get; set; }
        public Nullable<int> t_salida { get; set; }
    }
}
