//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trama2
    {
        public int ID { get; set; }
        public string IMEI { get; set; }
        public int EstadoGPS { get; set; }
        public double Velocidad { get; set; }
        public double Asimut { get; set; }
        public double Longitud { get; set; }
        public double Latitud { get; set; }
        public double Altitud { get; set; }
        public string TipoMensaje { get; set; }
        public string TipoRespuesta { get; set; }
        public int EstadoMotor { get; set; }
        public System.DateTime FechaGPS { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string IDButton { get; set; }
        public Nullable<bool> IDAutorizado { get; set; }
        public double Kilometraje { get; set; }
        public Nullable<decimal> RPMMotor { get; set; }
        public Nullable<decimal> ConsComb { get; set; }
        public Nullable<decimal> NivelEntradaComb { get; set; }
        public double Temperatura { get; set; }
        public double VoltajeBateria { get; set; }
        public bool EstadoPuerta { get; set; }
        public int Ultimo { get; set; }
        public string EstadoMotor1 { get; set; }
        public Nullable<int> DifIgnicion { get; set; }
    }
}
