//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISETRACK.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioVehiculo
    {
        public int id { get; set; }
        public string ci { get; set; }
        public string nroplaca { get; set; }
        public string nit { get; set; }
        public bool estado { get; set; }
        public string usuarioReg { get; set; }
        public System.DateTime fechaReg { get; set; }
        public string usuarioMod { get; set; }
        public Nullable<System.DateTime> fechaMod { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
